version: '3'
services:
  db:
    build: ./db
    container_name: db
    env_file:
      - ./db/.env
    ports:
      - 5432:5432

  server:
    build: ./server
    volumes:
      - ./server:/usr/src/server
      - /usr/src/server/node_modules
    tty: true
    container_name: server
    env_file:
      - ./server/.env
    environment:
      WAIT_HOSTS: db:5432 
    ports:
      - 4000:4000
    depends_on:
      - db
    links:
      - db